apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/khadythiara/test_sonarqube.git  # URL de votre dépôt
    targetRevision: main  # Branche à vérifier dans votre dépôt
    chart: Desktop/sa-devops/charts  # Assurez-vous que le chart est dans le dossier 'charts', sinon modifiez ce chemin
    helm:
      valueFiles:
        - values.yaml  # Vérifiez que ce fichier existe et est dans le bon emplacement
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-app-namespace  # Namespace où déployer l'application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

