apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/khadythiara/test_sonarqube.git
    targetRevision: main
    path: charts  # Assurez-vous que le chart est dans le dossier 'charts'
    helm:
      valueFiles:
        - values.yaml  # Vérifiez que ce fichier existe et est dans le bon répertoire
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

