version: '3.8'

services:
  # Service pour construire et exécuter l'application Java
  test_newman:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    networks:
      - test_newman-network

  # Service pour exécuter les tests Postman avec Newman
  newman:
    image: postman/newman_ubuntu1404
    volumes:
      - ./tests:/tests # Le dossier 'tests' sur votre machine hôte est monté dans le conteneur
    entrypoint: /bin/bash -c "apt-get update && apt-get install -y curl && curl -sL https://github.com/vishnubob/wait-for-it/raw/master/wait-for-it.sh -o /wait-for-it.sh && chmod +x /wait-for-it.sh && /wait-for-it.sh test_newman:8086 -- newman run /tests/Newman_collection.json --env-var 'BASE_URL=http://test_newman:8086'"
    depends_on:
      - test_newman
    networks:
      - test_newman-network

networks:
  app-network:
    driver: bridge
