apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
  labels:
    app: {{ .Values.appName }}
spec:
  capacity:
    storage: {{ .Values.pv.capacity }}
  accessModes:
    - {{ .Values.pv.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}
  hostPath:
    path: {{ .Values.pv.hostPath }}
