apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
        - name: k8s-app
          image: khadydiagne/k8s_app:latest
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: /data
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: k8s-app-pvc

