apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - host: k8s-app.sn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-app-service
            port:
              number: 8086 # Assurez-vous que cela correspond au port du service

